### ISSUE TITLE
[v4l2loopback] Failed to recognize file format

### ISSUE THREAD

**Issue by d4g** [ammen99/wf-recorder#101]
When I try to record the screen to a v4l2loopback device, something gets mixed up and I cannot successfully open the device:

```
crw-rw----+ 1 root video 81, 2 Jun 15 09:48 /dev/video2
```

The user is in the video group. I start recording via:

```
wf-recorder --muxer=v4l2 --codec=rawvideo --file=/dev/video2                                         ~
Please select an output from the list to capture (enter output no.):
1. Name: eDP-1 Description: Unknown 0x1536 0x00000000 (eDP-1)
2. Name: HDMI-A-1 Description: Dell Inc. DELL U2715H ... (HDMI-A-1)
Enter output no.:1
selected region 0 0 0 0
Choosing pixel format bgr0
Output #0, video4linux2,v4l2, to '/dev/video2':
    Stream #0:0: Unknown: none (rawvideo)
[video4linux2,v4l2 @ 0x7f9038000d00] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
```

I try to open the device via mpv:
```
mpv /dev/video2                                                                                      ~
Failed to recognize file format.
```

If I try the same on my integrated camera, it works:
```
mpv /dev/video0                                                                                      ~
 (+) Video --vid=1 (rawvideo 640x480 30.000fps)
[autoconvert] Converting yuyv422 -> yuv422p
VO: [gpu] 640x480 yuv422p
V: 00:00:02 / 00:00:02 (89%)
```

**Comment by ammen99** [comment]
Have you tried doing `ffplay /dev/video2` ?

**Comment by d4g** [comment]
It does work but I don't get any output:
```
ffplay /dev/video2                                                                                   ~
ffplay version 4.2.3 Copyright (c) 2003-2020 the FFmpeg developers
  built with gcc 9.3.0 (GCC)
  configuration: --disable-static --prefix=/nix/store/0n61jivjai7zp2bsykjhmrz8xq2rqccd-ffmpeg-full-4.2.3 --target_os=linux --arch=x86_64 --enable-gpl --enable-version3 --disable-nonfree --enable-shared --enable-pic --disable-small --enable-runtime-cpudetect --disable-lto --enable-gray --enable-swscale-alpha --enable-hardcoded-tables --enable-safe-bitstream-reader --enable-pthreads --disable-w32threads --disable-os2threads --enable-network --enable-pixelutils --enable-ffmpeg --enable-ffplay --enable-ffprobe --enable-avcodec --enable-avdevice --enable-avfilter --enable-avformat --enable-avresample --enable-avutil --enable-postproc --enable-swresample --enable-swscale --enable-doc --disable-htmlpages --enable-manpages --disable-podpages --disable-txtpages --enable-bzlib --enable-libcelt --enable-libdav1d --disable-libfdk-aac --disable-libflite --enable-fontconfig --enable-libfreetype --enable-frei0r --enable-libfribidi --enable-libgme --enable-gnutls --enable-libgsm --enable-ladspa --enable-libmp3lame --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libdc1394 --enable-iconv --enable-libjack --enable-libmfx --enable-libmodplug --enable-libmysofa --enable-libopus --enable-librsvg --enable-libssh --enable-libtheora --enable-libv4l2 --enable-vaapi --enable-vdpau --enable-libvorbis --enable-libvmaf --enable-libvpx --enable-libwebp --enable-xlib --enable-libxcb --enable-libxcb-shm --enable-libxcb-xfixes --enable-libxcb-shape --enable-lzma --enable-nvenc --enable-openal --enable-libopencore-amrnb --disable-opengl --enable-libopenjpeg --disable-openssl --enable-libpulse --enable-librtmp --enable-sdl2 --enable-libsoxr --enable-libspeex --enable-libvidstab --enable-libvo-amrwbenc --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-zlib --disable-debug --enable-optimizations --disable-extra-warnings --disable-stripping
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Input #0, video4linux2,v4l2, from '/dev/video2':B sq=    0B f=0/0   
  Duration: N/A, start: 5715.449393, bitrate: 3538944 kb/s
    Stream #0:0: Video: rawvideo (BGR[0] / 0x524742), bgr0, 2560x1440, 3538944 kb/s, 30 fps, 30 tbr, 1000k tbn, 1000k tbc
```

I also tried to configure the source in Firefox/Wire and did run into issues leading to the device disappearing in firefox.

**Comment by ammen99** [comment]
Try setting the output format to yuv420: `wf-recorder --muxer=v4l2 --codec=rawvideo --pixel-format=yuv420p --file=/dev/video2`

**Comment by d4g** [comment]
This works better, at least I could see something on at least one test page. But after a while, the camera disappeared in firefox. Probably a browser issue. I'll try how it works in chromium.

**Comment by d4g** [comment]
Ok, I think I found the issue. It did not work in chrome, as it did not appear to begin with.

After fiddling around, I found an answer:
According to
https://github.com/umlaeute/v4l2loopback/issues/78

You need to use exclusive_caps to be able to use the driver. After doing so, it works in both browsers.

Fix:
```
modprobe v4l2loopback exclusive_caps=1
```

**Comment by ammen99** [comment]
Alright, I assume the issue is fixed then? Closing, reopen if there is another bug in wf-recorder.

**Comment by d4g** [comment]
I still get the issue, that the device disappears in all browsers :( But I don't think this is due to wl-recorder. Probably more of an issue of the underlying technology, e.g. v4l2loopback
